modLoader="javafml"
loaderVersion="[29,)"
license="MIT"

[[mods]]
modId="damagetilt"
version="0.1.1"
displayName="DamageTilt"
authors="Charles445"
description='''
Tilts the player's camera when they take damage
'''

[[dependencies.damagetilt]]
modId="forge"
mandatory=true
versionRange="[29,)"
ordering="NONE"
side="BOTH"
   
[[dependencies.damagetilt]]
modId="minecraft"
mandatory=true
versionRange="[1.15, 1.16)"
ordering="NONE"
side="BOTH"
