modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="damagetilt"
version="0.1.1"
displayName="DamageTilt"
authors="Charles445"
description='''
Tilts the player's camera when they take damage
'''

[[dependencies.damagetilt]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"
   
[[dependencies.damagetilt]]
modId="minecraft"
mandatory=true
versionRange="[1.17, 1.18)"
ordering="NONE"
side="BOTH"
